export const T = {
  en: {
    title: "GRIDA",
    tagline: "COMPOSITION WITH YOUR DAY, YEAR, AND LIFE",
    loading: "Loading…",
    comingSoon: "Coming soon — this feature is on the way.",
    menu: { profile: "Profile", create: "New Mandalart", manage: "Manage", about: "About 'GridA'", mandalart: "Mandalart", planner: "Planner", pomodoro: "Pomodoro timer", setting: "Profile / User Guide" },
    back: "Back",
    replay: "Replay guide",
    categories: "Suggested categories",
    categoriesHint: "Tap one to drop it into an open slot",
    fullView: "Full grid",
    compactView: "Focus view",
    catList: [
      { k: "Health", d: "Sleep, fitness, nutrition" },
      { k: "Career", d: "Skills, role, milestones" },
      { k: "Finance", d: "Savings, income, habits" },
      { k: "Relationships", d: "Family, friends, community" },
      { k: "Growth", d: "Learning, mindset, reflection" },
      { k: "Hobby", d: "Creative outlets, play" },
      { k: "Mindset", d: "Discipline, calm, focus" },
      { k: "Travel", d: "Places, experiences" },
      { k: "Education", d: "Study, courses, knowledge" },
      { k: "Creativity", d: "Art, writing, music, design" },
      { k: "Spirituality", d: "Values, purpose, gratitude" },
      { k: "Social", d: "Networking, community impact" },
      { k: "Productivity", d: "Systems, tools, time management" },
      { k: "Leadership", d: "Influence, communication, vision" },
      { k: "Language", d: "Speaking, reading, listening" },
      { k: "Fitness", d: "Strength, flexibility, endurance" },
      { k: "Food", d: "Cooking, diet, meal habits" },
      { k: "Environment", d: "Space, organization, sustainability" },
      { k: "Rest", d: "Sleep, recovery, digital detox" },
      { k: "Passion Project", d: "Side venture, big idea, dream goal" },
    ],
    grid: {
      untitled: "Untitled Mandalart",
      mainGoal: "Main goal",
      subGoal: "Sub-goal",
      detail: "Detail",
      mobileTapHint: "Tap a sub-goal to open and edit its 8 action items.",
      mobileNoFullGrid: "The full 9×9 grid view isn't available on mobile.",
      saving: "Saving…",
      savedJustNow: "Saved just now",
      savedAgo: (s) => `Saved ${s}s ago`,
      unsaved: "Unsaved changes",
      save: "Save",
      descTitle: "Add a short note",
      descViewTitle: "Note",
      descPlaceholder: "What does this step actually involve?",
      descSave: "Save",
      descCancel: "Cancel",
      descClose: "Close",
      visPrivate: "Private",
      visPublic: "Public",
      visHintPrivate: "Only you can see this.",
      visHintPublic: "Friends can view this (no editing).",
    },
    manage: {
      title: "Your Mandalarts",
      empty: "Nothing here yet — create your first one.",
      open: "Open",
      create: "+ New mandalart",
      delete: "Delete",
      deleteConfirm: "Delete this mandalart? This cannot be undone.",
      deleteYes: "Yes, delete",
      deleteNo: "Cancel",
    },
    auth: {
      email: "Email",
      password: "Password",
      username: "Display name",
      usernameHint: "This name cannot be changed once set.",
      signIn: "Sign in",
      signUp: "Create account",
      signUpDone: "Check your inbox — we sent you a verification email. Click the link to activate your account.",
      toSignUp: "New here? Create an account",
      toSignIn: "Already have an account? Sign in",
      signOut: "Sign out",
      signOutConfirm: "Are you sure you want to sign out?",
      signOutYes: "Sign out",
      signOutNo: "Cancel",
      deleteAccount: "Delete account",
      deleteAccountReasonTitle: "Before you go — why are you deleting your account?",
      deleteAccountReasons: ["I no longer use it", "Missing features I need", "I found a better app", "Privacy concerns", "Other"],
      deleteAccountFeedbackPlaceholder: "Anything else you'd like to share? (optional)",
      deleteAccountNext: "Continue →",
      deleteAccountConfirm: "This will permanently delete your account and all data. This cannot be undone.",
      deleteAccountYes: "Delete permanently",
      deleteAccountNo: "Cancel",
      deleteAccountDeleting: "Deleting…",
      termsPrefix: "I agree to the",
      termsLink: "Terms of Use",
      termsRequired: "Please accept the Terms of Use to continue.",
      termsTitle: "Terms of Use",
      termsClauses: [
        "Your data (mandalarts, planner events, to-dos, pomodoro sessions) is stored securely on Supabase servers. We do not sell or share your personal data with third parties.",
        "Mandalarts are private by default. You control what is made public and visible to friends. Friends can only view your public content — never edit it.",
        "Time blocks and daily planner events reset at midnight each day. Monthly calendar events and to-dos are preserved.",
        "You may delete your account and all associated data at any time through the Profile page. Deletion is permanent and cannot be undone.",
        "Do not use 'GridA' for any unlawful, harmful, or abusive purpose.",
        "'GridA' is provided as-is. We are not liable for loss of data, session interruptions, or unintended use of the service.",
        "Background music tracks are original compositions. Some were produced with Suno AI as a base and further edited. All rights reserved.",
      ],
    },
    friends: {
      yourCode: "Your friend code",
      copy: "Copy",
      copied: "Copied",
      addTitle: "Add a friend",
      placeholder: "Name#0000",
      add: "Add",
      exactHint: "Enter their exact code — there's no name search, just like a Battle Tag.",
      errSelf: "That's your own code.",
      errNotFound: "No one found with that code.",
      errAlready: "You're already connected with this code.",
      sent: (code) => `Friend request sent to ${code}.`,
      requests: "Friend requests",
      accept: "Accept",
      decline: "Decline",
      list: "Friends",
      empty: "No friends yet — add one above.",
      statusAccepted: "Friends",
      statusPending: "Pending",
      viewMandalarts: "View mandalarts",
      viewerListTitle: (code) => `${code}'s public mandalarts`,
      viewerEmpty: "This friend hasn't made anything public yet.",
      viewerOpen: "Open",
      viewerBadge: "Public · view only",
    },
    onboarding: [
      { t: "Welcome to GridA", b: "One philosophy, three tools for living intentionally — turning goals, time, and focus into grids you fill in one cell at a time." },
      { t: "Mandalart", b: "Map your life in 81 cells. One central goal, 8 sub-goals, 64 concrete actions — your whole vision visible at once." },
      { t: "Planner", b: "Map your day in 144 ten-minute blocks. Mark time as you work, log events, and manage todos to see where your hours really go." },
      { t: "Pomodoro", b: "Focus one cell at a time. Name your task, set a duration, and work in structured intervals with real rest between them." },
      { t: "Ready to start", b: "Each tool has its own quick guide when you first open it. Pick one and place your first cell." },
      { t: "Install the app", b: "GridA works as an installable app — no app store needed. On Android, tap the Install button at the bottom of the screen. On iPhone, tap the Share icon in Safari and choose \"Add to Home Screen\"." },
    ],
    mandalartAbout: {
      title: "What is Mandalart?",
      body: [
        "A Mandalart is a 9×9 grid goal-setting technique built around one central goal, broken into 8 sub-goals, each of which is further broken into 8 concrete action items. It originated in Japan in the 1980s and became widely known after baseball player Shohei Ohtani's own Mandalart from his high school years was publicized.",
        "This app's grid follows one rule: the 8 cells around your main goal are directly linked to the center cell of each of the 8 outer blocks — edit one and the other updates too. Eight separate paths, converging on one goal.",
        "Write entries in the present tense, as if already achieved, rather than as something you intend to do. It changes how you act toward them.",
        "Visualizing your goals through a Mandalart actually increases your chances of achieving them. It also helps you map out how each daily habit connects to your core goal. When vague intentions become a concrete, visible plan, they're harder to ignore and much easier to act on.",
      ],
      tipsTitle: "Quick tips",
      tips: [
        "Start with your main goal in the center. Make it specific and personal.",
        "Fill in the 8 surrounding sub-goals before touching any outer block.",
        "Use the suggested categories as a starting point, not a constraint.",
        "Link related cells with the ⛓ icon to jump between them instantly.",
        "Set your mandalart to Public so trusted friends can see your progress.",
        "Play background music to enter a focused, distraction-free writing state.",
      ],
      ohtaniLabel: "The Ohtani method",
      ohtani: "Shohei Ohtani created his Mandalart at age 16 with the goal of being drafted #1 by all 8 pro teams. His 8 sub-goals included nutrition, mental strength, speed, and pitching power — each broken into 8 concrete daily habits. He achieved it: drafted in 2013, he went on to become one of the greatest baseball players in history — a two-way MLB superstar who signed the largest contract in sports history ($700M, LA Dodgers) and won the World Series in 2024.",
      ohtaniGridLabel: "Ohtani's actual Mandalart",
      ohtaniGridCaption: "Goal: be drafted #1 by all 8 pro teams. 8 sub-goals, 64 daily habits.",
      ohtaniGridCta: "Use this as a reference — then start filling in your own.",
      btn: "What is Mandalart?",
    },
    about: {
      title: "About 'GridA'",
      intro: "One philosophy. Three tools. A complete system for living intentionally.",
      philosophy: {
        title: "The Grid Philosophy",
        body: "Inspired by Piet Mondrian's De Stijl — which reduced all of painting to grids, primary colors, and black lines — 'GridA' reduces the complexity of life to its essential structure. Goals, time, and focus: each expressed as a grid, each designed to be filled in one cell at a time.",
      },
      features: [
        {
          tag: "Mandalart",
          title: "Your life in 81 cells",
          body: "Define one central goal. Break it into 8 sub-goals. Break each into 8 concrete actions. The result is a complete map from vision to daily habit — everything visible at once, nothing left vague.",
          benefits: ["Clarifies what truly matters", "Aligns big goals with daily actions", "Makes abstract ambitions concrete and visible"],
        },
        {
          tag: "Planner",
          title: "Your day in 144 blocks",
          body: "Every day has 144 ten-minute blocks. Map them intentionally — mark time blocks as you work, log events, manage todos. See exactly where your hours go and close the gap between what you planned and what actually happened.",
          benefits: ["Builds honest awareness of how time is spent", "Reduces decision fatigue throughout the day", "Bridges long-term goals with today's schedule"],
        },
        {
          tag: "Pomodoro",
          title: "Your focus, one cell at a time",
          body: "Name what you're working on. Set your duration. Watch the grid drain. Structured focus intervals with real rest between them — the proven method for deep, sustained work without burning out.",
          benefits: ["Trains single-task concentration", "Makes work sessions feel finite and achievable", "Builds momentum through small, visible completions"],
        },
      ],
    },
    mandalartGuide: {
      steps: [
        { t: "Create & manage", b: "Tap 'New Mandalart' to start a fresh grid. You can have multiple mandalarts — switch between them anytime from this management screen." },
        { t: "Fill the grid", b: "Start with your main goal in the center, then work outward: 8 sub-goals, then 64 concrete action items. Use Full Grid view to see everything at once, or Focus view to work one block at a time." },
        { t: "Track & check off", b: "In Focus view, mark each action item complete with the check icon. Completed sub-goals earn a badge. Your progress is visible across the entire 9×9 grid." },
        { t: "Share with friends", b: "Set a mandalart to Public and share it with friends using your unique friend code. Friends can view your progress — great for accountability." },
      ],
      dontShow: "Don't show this when entering Mandalart",
      showAgain: "Show guide",
      close: "Start",
    },
    gridTutorial: {
      steps: [
        { t: "Step 1 — Set your main goal", b: "Click the center cell of the center block and write your single most important goal. Be specific and personal." },
        { t: "Step 2 — Define 8 sub-goals", b: "The 8 cells around the center become your sub-goals. They automatically link to the centers of the 8 surrounding blocks." },
        { t: "Step 3 — Add 64 action items", b: "For each sub-goal block, fill its surrounding 8 cells with concrete daily actions. These are the habits that compound into real progress." },
        { t: "Write as if it's done", b: "Phrase every entry in the present tense — as if already achieved. It shifts how you think about and work toward each goal." },
        { t: "Full Grid vs Focus view", b: "Toggle between Full Grid (all 81 cells at once) and Focus view (one block at a time). In Focus view, use the minimap on the left to jump between blocks." },
        { t: "Track your progress", b: "In Focus view, tap the check icon (bottom-right of any detail cell) to mark it complete. A bold checkmark appears over the cell and the background shifts — see progress across all 81 cells at a glance. A small colored dot in the top-right corner means the cell has a memo attached." },
        { t: "Reorder sub-goals", b: "In the center block, each sub-goal cell has a grip handle (⠿) in the bottom-left corner. Drag it onto another sub-goal to swap the two blocks — all 8 action items and their data move together. Works in both Focus and Full Grid view." },
      ],
      dontShow: "Don't show this when creating new mandalarts",
      showAgain: "Show tutorial",
      close: "Got it, let's go",
    },
    planner: {
      resetNote: "Time blocks and events reset at midnight each day.",
      tabDaily: "Daily", tabMonthly: "Monthly",
      viewModeBtn: "View mode", editModeBtn: "Edit mode",
      timeBlocks: "Time blocks", eventsCol: "Events", todoCol: "To-do",
      noEvents: "No events — drag on the grid to add one",
      noTodos: "Nothing here yet",
      eventTitlePlaceholder: "Event name",
      eventMemoPlaceholder: "Notes (optional)",
      save: "Add", cancel: "Cancel",
      todoPlaceholder: "Add a task…",
      addEvent: "Add event",
      tabEvents: "Events", tabRecurring: "Recurring",
      recurringTitlePlaceholder: "Event name",
      addRecurring: "Add recurring",
      selectDate: "Select a date to view or add events.",
      fromCalendar: "From calendar",
      moveTomorrow: "Procrastinate",
      delete: "Delete",
      notifStartTitle: "Event starting now",
      notifStartBody: (title) => `It's time for "${title}".`,
      days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    },
    plannerGuide: {
      steps: [
        { t: "Set time blocks", b: "Drag across the grid to select multiple cells, or double-click for a single cell. The event popup appears as soon as you release." },
        { t: "Add an event", b: "Enter a title, pick a color, and add optional notes. Hit Add and the blocks are colored and your event appears in the list." },
        { t: "Manage to-dos", b: "To-dos are global — they persist across dates. Check to complete, × to delete. Add as many as you need." },
        { t: "Monthly view & recurring", b: "In the Monthly tab, add events to future dates or set recurring events by day of week. They'll appear automatically in the daily view on the right day." },
      ],
      mobileSteps: [
        { t: "Scrolling the grid", b: "Dragging on the grid selects time blocks, so use the SCROLL rail on the right edge to scroll the day up and down." },
        { t: "Procrastinate & delete", b: "In the Events list, swipe an event left to delete it, or swipe right to procrastinate — moving it to the same time tomorrow." },
      ],
      dontShow: "Don't show this when entering Planner",
      showAgain: "Show guide",
      close: "Let's plan",
    },
    pomodoroGuide: {
      steps: [
        { t: "Set your focus time", b: "Drag across the grid to set your session length. Each cell is 1 minute — up to 45 minutes total. You can adjust it any time before starting." },
        { t: "Name your focus", b: "Type what you're working on in the goal field at the top. Naming your focus makes it real and keeps you anchored during the session." },
        { t: "Watch time flow", b: "Press Start and watch the grid drain in real time. The active cell empties smoothly as seconds pass, then disappears when the minute is up." },
        { t: "Rest for real", b: "When the timer ends, you'll hear a sound and get a notification. Step away. Don't skip the break — rest is part of the system." },
        { t: "Locking in", b: "Switch to the Locking-in tab for a count-up stopwatch. Set a focus goal, press Start, and the hour/minute/second grid fills as you go. It only runs while this tab is open — save sessions to your Archive." },
      ],
      dontShow: "Don't show this when entering Pomodoro",
      showAgain: "Show guide",
      close: "Let's focus",
    },
    music: { off: "Off", loopNote: "Loops until stopped" },
    guide: {
      btnLabel: "How to use",
      title: "Feature Guide",
      tabGuide: "Guide",
      tabContact: "Contact",
      tabTerms: "Terms",
      contactFormTitle: "Send a message",
      contactSubjectPlaceholder: "Subject",
      contactMessagePlaceholder: "Describe your question or feedback…",
      contactBtn: "Send",
      contactSending: "Sending…",
      contactSentConfirm: "Message sent!",
      contactError: "Failed to send. Please try again.",
      contactHistory: "Your messages",
      contactPending: "Pending",
      contactReplied: "Replied",
      contactAdminReply: "Reply",
      sections: [
        {
          category: "General",
          items: [
            { t: "Themes & Appearance", b: "Switch between 6 themes (Mondrian, Neptune, Mars, Earth, Venus, Mercury) and toggle dark/light mode or language (EN/KO) from the top bar on any screen." },
            { t: "Sound & Music", b: "Toggle sound on/off and select a background music track — it loops until you stop it. Some tracks were produced with Suno AI as a base and further edited by hand." },
            { t: "Friends & Sharing", b: "Share your friend code from the Profile page. Friends you add can view your public content. They cannot edit anything — view only." },
            { t: "Saving", b: "Your work auto-saves when your connection is stable. After major edits, press the save button to be safe. Refreshing the page always returns you to the home screen." },
          ],
        },
        {
          category: "Planner",
          items: [
            { t: "Time Blocks", b: "Drag across the grid to mark time slots — each cell is 30 minutes. Double-click a single cell to add a quick event. Release to open the event form." },
            { t: "Events & To-dos", b: "Events are tied to specific dates. To-dos are global and persist across dates. Check to complete, × to delete." },
            { t: "Monthly View & Recurring", b: "In the Monthly tab, add events to future dates or set events that repeat by day of week. They appear automatically in the daily view on the right day." },
            { t: "Midnight Reset", b: "Time blocks and events in the daily view reset at midnight each day. To-dos and monthly calendar events are not affected." },
          ],
        },
        {
          category: "Mandalart",
          items: [
            { t: "9×9 Grid", b: "The center cell is your main goal. The 8 surrounding cells are sub-goals — each links directly to the center of an outer block. Edit either side and both update instantly." },
            { t: "Focus View", b: "Switch to Focus view to edit one outer block at a time with a minimap on the left. Great for deep work on a single sub-goal without distraction." },
            { t: "Cell Notes", b: "Tap the sticky-note icon on any detail cell to add a longer note. A small dot appears on the cell when a note is saved." },
            { t: "Manage", b: "Create multiple mandalarts from the Manage page. Each is saved separately and can be opened or deleted independently." },
            { t: "Sharing", b: "Set a mandalart to Public so friends can view it from their Profile page. Friends cannot edit it — view only." },
          ],
        },
        {
          category: "Pomodoro",
          items: [
            { t: "Setting Duration", b: "Drag across the grid to set your session length. Each cell is 1 minute — up to 45 minutes total. You can adjust it before starting." },
            { t: "Focus Goal", b: "Type what you're working on in the goal field at the top. Naming your focus keeps you anchored during the session." },
            { t: "Timer", b: "Press Start and watch the grid drain in real time. The active cell empties as seconds pass, then disappears when the minute is up." },
            { t: "Breaks", b: "When the timer ends, you'll hear a sound and receive a notification. Step away — rest is part of the system." },
          ],
        },
      ],
    },
    splash: { cta: "Click anywhere to begin writing your Mandalart." },
    next: "Next", prev: "Back", start: "Start writing", skip: "Skip",
    sound: "Sound", lang: "Language", theme: "Theme", dark: "Dark", light: "Light",
    settings: "Settings", notifications: "Notifications",
    install: {
      title: "Install GridA",
      body: "Add to your home screen for the full app experience.",
      install: "Install",
      iosHint: "Tap",
      iosHint2: "then \"Add to Home Screen\"",
    },
    pomodoro: {
      goalPlaceholder: "What are you focusing on?",
      start: "Start",
      pause: "Pause",
      resume: "Resume",
      reset: "Reset",
      done: "Time's up!",
      minutesLeft: (n) => `${n} min left`,
      notifTitle: "'GridA' — Time's up!",
      notifBody: (goal) => goal ? `Focus session complete: "${goal}"` : "Your Pomodoro session is complete.",
      notifPermission: "Enable notifications to get alerted when time is up.",
      lockin: {
        modeTimer: "Timer",
        modeLockin: "Locking in",
        goalLabel: "Focus goal",
        goalSet: "Set a focus goal, then press Start.",
        start: "Start",
        pause: "Pause",
        resume: "Resume",
        reset: "Reset",
        save: "Save record",
        saved: "Saved!",
        archive: "Archive",
        congrats: "🎉 Goal reached — keep going!",
        hint: "The stopwatch runs only while this tab is open and active.",
        elapsed: "Focused",
        archiveTitle: "Focus archive",
        archiveEmpty: "No saved sessions yet.",
        close: "Close",
        of: "of",
        unitH: "Hours",
        unitM: "Minutes",
        unitS: "Seconds",
      },
      about: {
        title: "What is the Pomodoro Technique?",
        body: [
          "The Pomodoro Technique is a time management method developed by Francesco Cirillo in the late 1980s. You work in focused intervals — typically 25 minutes — then take a short break. The name comes from the tomato-shaped kitchen timer he used as a student.",
          "In GridA, one block equals one minute. Drag across the grid to set your focus duration, then watch the blocks clear as time passes. The visual rhythm helps you stay anchored to the present moment.",
          "During a session, single-task. If something else comes up, jot it down and deal with it in a break. After the timer ends, take a real break — avoid addictive distractions.",
        ],
        tipsTitle: "Tips",
        tips: [
          "Set a clear goal at the top before starting.",
          "Close other tabs and silence notifications.",
          "If you get distracted, don't restart — just refocus.",
          "Take genuine breaks between sessions. Don't skip them.",
        ],
        warningTitle: "Important",
        warning: "During a session: no multitasking. If something comes to mind, write it down and handle it during a break. Rest time is for actual rest — not social media or videos.",
      },
    },
  },
  ko: {
    title: "GRIDA",
    tagline: "하루와 일 년, 그리고 인생을 그리다",
    loading: "불러오는 중…",
    comingSoon: "곧 만나요 — 준비 중인 기능이에요.",
    menu: { profile: "프로필", create: "새 만다라트", manage: "만다라트 관리", about: "'그리다'(GridA) 소개", mandalart: "만다라트", planner: "플래너", pomodoro: "뽀모도로 타이머", setting: "프로필 / 사용 가이드" },
    back: "뒤로",
    replay: "가이드 다시 보기",
    categories: "추천 카테고리",
    categoriesHint: "탭하면 빈 칸에 채워져요",
    fullView: "전체 보기",
    compactView: "포커스 보기",
    catList: [
      { k: "건강", d: "수면, 운동, 영양" },
      { k: "커리어", d: "역량, 직무, 마일스톤" },
      { k: "재정", d: "저축, 수입, 습관" },
      { k: "관계", d: "가족, 친구, 공동체" },
      { k: "성장", d: "학습, 마인드셋, 회고" },
      { k: "취미", d: "창작, 여가" },
      { k: "마인드셋", d: "규율, 평정심, 집중" },
      { k: "여행", d: "장소, 경험" },
      { k: "교육", d: "공부, 강의, 지식" },
      { k: "창의성", d: "미술, 글쓰기, 음악, 디자인" },
      { k: "영성", d: "가치관, 목적, 감사" },
      { k: "소셜", d: "네트워킹, 커뮤니티 참여" },
      { k: "생산성", d: "시스템, 도구, 시간 관리" },
      { k: "리더십", d: "영향력, 소통, 비전" },
      { k: "언어", d: "말하기, 읽기, 듣기" },
      { k: "체력", d: "근력, 유연성, 지구력" },
      { k: "식습관", d: "요리, 식단, 식사 습관" },
      { k: "환경", d: "공간, 정리, 지속가능성" },
      { k: "회복", d: "수면, 휴식, 디지털 디톡스" },
      { k: "사이드 프로젝트", d: "부업, 큰 아이디어, 꿈의 목표" },
    ],
    grid: {
      untitled: "제목 없는 만다라트",
      mainGoal: "메인 목표",
      subGoal: "하위 목표",
      detail: "세부 항목",
      mobileTapHint: "하위 목표를 누르면 8개의 실천 항목을 열어 편집할 수 있어요.",
      mobileNoFullGrid: "전체 9×9 그리드 보기는 모바일에서 지원하지 않아요.",
      saving: "저장 중…",
      savedJustNow: "방금 저장됨",
      savedAgo: (s) => `${s}초 전 저장됨`,
      unsaved: "저장되지 않은 변경사항",
      save: "저장",
      descTitle: "짧은 설명 추가",
      descViewTitle: "메모",
      descPlaceholder: "이 단계가 구체적으로 어떤 걸 의미하나요?",
      descSave: "저장",
      descCancel: "취소",
      descClose: "닫기",
      visPrivate: "비공개",
      visPublic: "공개",
      visHintPrivate: "나만 볼 수 있어요.",
      visHintPublic: "친구들이 볼 수 있어요 (수정은 불가).",
    },
    manage: {
      title: "내 만다라트",
      empty: "아직 없어요 — 첫 만다라트를 만들어보세요.",
      open: "열기",
      create: "+ 새 만다라트",
      delete: "삭제",
      deleteConfirm: "이 만다라트를 삭제할까요? 되돌릴 수 없어요.",
      deleteYes: "삭제",
      deleteNo: "취소",
    },
    auth: {
      email: "이메일",
      password: "비밀번호",
      username: "표시 이름",
      usernameHint: "한번 설정한 이름은 변경할 수 없어요.",
      signIn: "로그인",
      signUp: "계정 만들기",
      signUpDone: "받은 편지함을 확인해주세요 — 인증 이메일을 보냈어요. 링크를 클릭하면 계정이 활성화돼요.",
      toSignUp: "처음이신가요? 계정 만들기",
      toSignIn: "이미 계정이 있으신가요? 로그인",
      signOut: "로그아웃",
      signOutConfirm: "정말 로그아웃 하시겠어요?",
      signOutYes: "로그아웃",
      signOutNo: "취소",
      deleteAccount: "계정 삭제",
      deleteAccountReasonTitle: "떠나시기 전에 — 삭제하시는 이유를 알려주세요.",
      deleteAccountReasons: ["더 이상 사용하지 않아요", "필요한 기능이 없어요", "더 좋은 앱을 찾았어요", "개인정보가 걱정돼요", "기타"],
      deleteAccountFeedbackPlaceholder: "추가로 하고 싶은 말이 있다면 적어주세요. (선택)",
      deleteAccountNext: "계속 →",
      deleteAccountConfirm: "계정과 모든 데이터가 영구적으로 삭제되며 되돌릴 수 없어요.",
      deleteAccountYes: "영구 삭제",
      deleteAccountNo: "취소",
      deleteAccountDeleting: "삭제 중…",
      termsPrefix: "아래 이용약관에 동의해요:",
      termsLink: "이용약관",
      termsRequired: "계속하려면 이용약관에 동의해주세요.",
      termsTitle: "이용약관",
      termsClauses: [
        "만다라트, 플래너 일정, 할 일, 뽀모도로 세션 등 모든 데이터는 Supabase 서버에 안전하게 저장되며, 제3자에게 제공되거나 판매되지 않습니다.",
        "만다라트는 기본적으로 비공개입니다. 공개 여부는 직접 설정할 수 있으며, 친구는 공개된 콘텐츠를 보기만 할 수 있고 수정은 불가능합니다.",
        "일간 플래너의 타임 블럭과 일정은 매일 자정에 초기화됩니다. 월간 캘린더 일정과 할 일은 유지됩니다.",
        "프로필 페이지에서 언제든지 계정 및 모든 데이터를 영구 삭제할 수 있습니다. 삭제는 되돌릴 수 없습니다.",
        "'그리다'(GridA)를 불법적이거나 유해한 목적으로 사용하지 않습니다.",
        "'그리다'(GridA)는 현 상태로 제공되며, 데이터 손실, 세션 중단, 또는 의도치 않은 사용으로 인한 책임을 지지 않습니다.",
        "배경 음악은 자체 제작된 곡들입니다. 일부는 Suno AI를 베이스로 추가 편집해 제작됐습니다. 모든 권리는 제작자에게 있습니다.",
      ],
    },
    friends: {
      yourCode: "내 친구 코드",
      copy: "복사",
      copied: "복사됨",
      addTitle: "친구 추가",
      placeholder: "이름#0000",
      add: "추가",
      exactHint: "정확한 코드를 입력해야 해요 — 이름으로는 검색할 수 없어요.",
      errSelf: "본인 코드예요.",
      errNotFound: "해당 코드를 가진 사용자가 없어요.",
      errAlready: "이미 연결된 코드예요.",
      sent: (code) => `${code}님께 친구 요청을 보냈어요.`,
      requests: "받은 친구 요청",
      accept: "수락",
      decline: "거절",
      list: "친구 목록",
      empty: "아직 친구가 없어요 — 위에서 추가해보세요.",
      statusAccepted: "친구",
      statusPending: "대기 중",
      viewMandalarts: "만다라트 보기",
      viewerListTitle: (code) => `${code}님의 공개 만다라트`,
      viewerEmpty: "아직 공개로 설정한 만다라트가 없어요.",
      viewerOpen: "열기",
      viewerBadge: "공개 · 보기 전용",
    },
    onboarding: [
      { t: "그리다에 오신 걸 환영해요", b: "하나의 철학, 세 가지 도구로 의도적으로 살아가요. 목표·시간·집중을 한 칸씩 채워가는 그리드로 바꿔요." },
      { t: "만다라트", b: "81칸에 인생을 펼쳐요. 하나의 핵심 목표, 8개의 세부 목표, 64개의 구체적 행동을 한눈에 봐요." },
      { t: "플래너", b: "하루를 144개의 10분 블록으로 그려요. 작업한 시간을 표시하고, 일정을 기록하고, 할 일을 관리하며 시간이 어디로 가는지 봐요." },
      { t: "뽀모도로", b: "한 번에 한 칸씩 집중해요. 할 일을 적고, 시간을 정하고, 충분한 휴식이 있는 구조화된 집중 구간으로 일해요." },
      { t: "시작할 준비 됐어요", b: "각 도구는 처음 열 때 간단한 가이드를 보여줘요. 하나를 골라 첫 칸을 채워보세요." },
      { t: "앱으로 설치하기", b: "GridA는 앱스토어 없이 설치할 수 있어요. 안드로이드는 화면 하단의 설치 버튼을 탭하세요. 아이폰은 Safari 하단 공유 버튼 → \"홈 화면에 추가\"를 선택하면 돼요." },
    ],
    mandalartAbout: {
      title: "만다라트란?",
      body: [
        "만다라트는 하나의 핵심 목표를 중심에 두고, 그것을 이루기 위한 8개의 하위 목표, 그리고 각 하위 목표를 다시 8개의 구체적인 실행 항목으로 쪼개는 9×9 격자 형태의 목표 설정 기법이에요. 1980년대 일본에서 만들어졌고, 야구선수 오타니 쇼헤이가 고교 시절 작성한 만다라트가 알려지면서 널리 퍼졌어요.",
        "이 앱의 그리드는 한 가지 원칙을 따라요 — 메인 목표 둘레의 8칸은 바깥에 있는 8개 블록 각각의 중심 칸과 그대로 연결돼 있어서, 한쪽을 고치면 다른 쪽도 같이 바뀌어요. 여덟 갈래로 흩어진 하위 목표들이 결국 하나의 중심으로 수렴한다는 뜻이에요.",
        "목표를 쓸 때는 '할 거야'가 아니라 '이미 하고 있어'처럼 현재형으로 적어보세요. 그렇게 쓴 말이 생각과 행동 모두를 바꿔요.",
        "만다라트를 통해 목표를 시각화하는 것은 실제로 목표를 달성할 확률을 높여줘요. 또한 만다라트는 일상 습관 하나하나가 핵심 목표로 어떻게 이어지는지를 직접 그려가게 해요. 막연한 의지가 눈에 보이는 구체적인 계획이 되면, 외면하기도 어렵고 실행하기도 훨씬 쉬워져요.",
      ],
      tipsTitle: "빠른 팁",
      tips: [
        "중앙에 메인 목표부터 적어보세요. 구체적이고 내 것이어야 해요.",
        "바깥 블록을 채우기 전에, 메인 목표 주변 8칸(하위 목표)부터 완성하세요.",
        "추천 카테고리는 출발점이지, 제약이 아니에요. 자유롭게 수정하세요.",
        "⛓ 아이콘으로 연관된 칸을 연결하면 한 번에 이동할 수 있어요.",
        "완성한 만다라트를 공개로 설정하면, 친구들과 목표를 나눌 수 있어요.",
        "배경 음악을 틀면 집중력 있는 글쓰기 상태에 더 쉽게 들어갈 수 있어요.",
      ],
      ohtaniLabel: "오타니 방식",
      ohtani: "오타니 쇼헤이는 고교 시절 '8개 구단 드래프트 1순위 지명'을 목표로 만다라트를 작성했어요. 영양, 멘탈, 스피드, 구위 등 8개의 하위 목표, 각각을 위한 64가지 일상 습관으로 구체화했어요. 그리고 그는 실제로 해냈어요. 2013년 드래프트 1순위로 지명된 그는 이후 MLB에서 투수와 타자를 동시에 소화하는 역대 최고의 이도류 선수가 됐고, 스포츠 역사상 최대 규모의 계약(7억 달러, LA 다저스)을 맺은 뒤 2024년 월드 시리즈 우승까지 거머쥐었어요.",
      ohtaniGridLabel: "오타니의 실제 만다라트 (고교 시절)",
      ohtaniGridCaption: "목표: 8개 구단 드래프트 1순위 지명. 8개 하위 목표, 64가지 일상 습관.",
      ohtaniGridCta: "이 만다라트를 참고해서, 나만의 만다라트를 작성해보세요.",
      btn: "만다라트란?",
    },
    about: {
      title: "'그리다'(GridA) 소개",
      intro: "하나의 철학. 세 가지 도구. 의도적으로 살기 위한 완전한 시스템.",
      philosophy: {
        title: "격자의 철학",
        body: "몬드리안의 신조형주의(De Stijl)는 회화의 모든 것을 격자와 원색, 검은 선으로 환원했어요. '그리다'(GridA)는 같은 방식으로 삶의 복잡함을 그 본질적인 구조로 환원합니다. 목표, 시간, 집중 — 각각을 격자로 표현하고, 한 칸씩 채워나가도록 설계했어요.",
      },
      features: [
        {
          tag: "만다라트",
          title: "81칸에 담은 내 인생",
          body: "하나의 핵심 목표를 정하세요. 이를 8개의 하위 목표로 쪼개고, 각 하위 목표를 다시 8개의 구체적인 행동으로 나누세요. 비전부터 일상 습관까지의 전체 지도가 한눈에 보여요. 막연한 것은 하나도 없어요.",
          benefits: ["진짜 중요한 것을 명확히 합니다", "큰 목표와 일상의 행동을 연결합니다", "추상적인 꿈을 눈에 보이는 계획으로 만들어줍니다"],
        },
        {
          tag: "플래너",
          title: "144칸에 담은 내 하루",
          body: "하루는 144개의 10분 블록으로 이루어져 있어요. 타임 블록·일정·할 일을 한 화면에서 의도적으로 채워보세요. 내 시간이 어디로 가는지 정확히 보이고, 계획과 실제 사이의 간극도 보여요.",
          benefits: ["시간이 어떻게 쓰이는지 솔직하게 인식하게 합니다", "하루 종일 의사결정 피로를 줄여줍니다", "장기 목표와 오늘의 일정을 연결합니다"],
        },
        {
          tag: "뽀모도로",
          title: "지금 이 순간, 한 칸씩",
          body: "지금 하는 일을 적으세요. 시간을 설정하세요. 격자가 줄어드는 것을 지켜보세요. 집중 인터벌과 진짜 휴식을 번갈아 반복하는 것 — 지치지 않고 깊게 일하는 검증된 방법이에요.",
          benefits: ["단일 과제 집중력을 키웁니다", "작업 시간을 유한하고 달성 가능하게 만들어줍니다", "작은 완료의 반복으로 추진력을 만들어줍니다"],
        },
      ],
    },
    mandalartGuide: {
      steps: [
        { t: "만들기 & 관리", b: "'새 만다라트' 버튼으로 새 그리드를 시작할 수 있어요. 여러 개의 만다라트를 만들고, 이 관리 화면에서 언제든 전환할 수 있어요." },
        { t: "격자 채우기", b: "중앙에 핵심 목표를 적고 바깥으로 넓혀가세요 — 8개의 하위 목표, 그리고 64가지 구체적인 실행 항목 순서로요. 전체 그리드 뷰로 81칸을 한눈에, 포커스 뷰로 블록 하나씩 집중해서 작성할 수 있어요." },
        { t: "진행 상황 체크", b: "포커스 뷰에서 실행 항목별로 완료 체크를 할 수 있어요. 하위 목표 8개가 모두 완료되면 뱃지가 붙어요. 9×9 그리드 전체에서 진행 상황을 한눈에 볼 수 있어요." },
        { t: "친구와 공유", b: "만다라트를 '공개'로 설정하고, 나만의 친구 코드로 친구를 추가해보세요. 친구가 내 진행 상황을 볼 수 있어 서로 동기부여가 돼요." },
      ],
      dontShow: "만다라트 진입 시 자동으로 표시 안 함",
      showAgain: "가이드 보기",
      close: "시작하기",
    },
    gridTutorial: {
      steps: [
        { t: "Step 1 — 메인 목표 설정", b: "중앙 블록의 가운데 칸을 클릭해 가장 중요한 목표를 하나 적어요. 구체적이고 내 것이어야 해요." },
        { t: "Step 2 — 8개의 하위 목표", b: "중앙 칸 주변 8칸이 하위 목표가 돼요. 이 칸들은 바깥 8개 블록의 중심 칸과 자동으로 연결돼 있어요." },
        { t: "Step 3 — 64가지 실행 항목", b: "각 하위 목표 블록의 나머지 8칸에 구체적인 일상 행동을 적어요. 64가지 습관이 쌓여 진짜 변화가 만들어져요." },
        { t: "이미 이룬 것처럼 써요", b: "모든 항목을 현재형으로 — 이미 달성한 것처럼 적어보세요. 생각과 행동 방식이 달라져요." },
        { t: "전체 그리드 vs 포커스 뷰", b: "전체 그리드(81칸 한눈에 보기)와 포커스 뷰(블록 하나씩 집중 편집) 사이를 자유롭게 전환할 수 있어요. 포커스 뷰에서는 왼쪽 미니맵으로 블록 간 이동이 가능해요." },
        { t: "진행 상황 체크", b: "포커스 뷰에서 세부 실행 칸 오른쪽 아래의 체크 아이콘을 누르면 완료 표시가 돼요. 굵은 체크 표시가 칸 위에 나타나고 배경색이 바뀌어서, 81칸 전체의 진행 상황을 한눈에 볼 수 있어요. 오른쪽 위의 작은 색 점은 해당 칸에 메모가 있다는 뜻이에요." },
        { t: "하위 목표 순서 바꾸기", b: "센터 블록의 하위 목표 칸 왼쪽 아래에는 핸들(⠿)이 있어요. 이걸 드래그해서 다른 하위 목표 칸에 드롭하면 두 블록 전체가 자리를 바꿔요 — 8개의 세부 실행 항목과 메모, 완료 상태가 모두 함께 이동해요. 포커스 뷰와 전체 그리드 뷰 모두에서 사용 가능해요." },
      ],
      dontShow: "다음부터 자동으로 표시 안 함",
      showAgain: "튜토리얼 보기",
      close: "시작하기",
    },
    planner: {
      resetNote: "타임 블록과 일정은 매 자정에 초기화돼요.",
      tabDaily: "일일", tabMonthly: "월간",
      viewModeBtn: "보기 모드", editModeBtn: "편집 모드",
      timeBlocks: "타임 블록", eventsCol: "일정", todoCol: "할 일",
      noEvents: "일정 없음 — 격자 위를 드래그해서 추가하세요",
      noTodos: "할 일이 없어요",
      eventTitlePlaceholder: "일정 이름",
      eventMemoPlaceholder: "메모 (선택)",
      save: "추가", cancel: "취소",
      todoPlaceholder: "할 일 추가…",
      addEvent: "일정 추가",
      tabEvents: "일정", tabRecurring: "반복 일정",
      recurringTitlePlaceholder: "일정 이름",
      addRecurring: "반복 일정 추가",
      selectDate: "날짜를 선택해 일정을 확인하거나 추가하세요.",
      fromCalendar: "캘린더에서",
      moveTomorrow: "내일로 미루기",
      delete: "삭제",
      notifStartTitle: "일정 시작",
      notifStartBody: (title) => `"${title}" 시작할 시간이에요.`,
      days: ["일", "월", "화", "수", "목", "금", "토"],
      months: ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
    },
    plannerGuide: {
      steps: [
        { t: "타임 블록 설정", b: "격자 위를 드래그하면 여러 칸을, 더블클릭하면 한 칸을 선택할 수 있어요. 선택이 끝나면 일정 추가 팝업이 바로 떠요." },
        { t: "일정 등록", b: "제목과 색상, 메모를 입력하고 추가 버튼을 누르면 일정이 생성돼요. 타임 블록에 색상이 칠해지고 일정 목록에도 표시돼요." },
        { t: "할 일 관리", b: "할 일은 날짜와 무관하게 전역으로 유지돼요. 체크로 완료 표시하고, × 버튼으로 삭제할 수 있어요." },
        { t: "월간 뷰 & 반복 일정", b: "월간 탭에서 미래 날짜의 일정을 미리 등록하거나 요일 기반 반복 일정을 설정할 수 있어요. 해당 날짜가 되면 일일 뷰에 자동으로 표시돼요." },
      ],
      mobileSteps: [
        { t: "격자 스크롤하기", b: "격자를 드래그하면 타임 블록이 선택돼요. 그래서 화면을 위아래로 스크롤하려면 오른쪽 가장자리의 SCROLL 레일을 사용하세요." },
        { t: "내일로 미루기 & 삭제", b: "일정 목록에서 일정을 왼쪽으로 밀면 삭제, 오른쪽으로 밀면 '내일로 미루기'(내일 같은 시간으로 이동)예요." },
      ],
      dontShow: "플래너 진입 시 자동으로 표시 안 함",
      showAgain: "가이드 보기",
      close: "시작하기",
    },
    pomodoroGuide: {
      steps: [
        { t: "집중 시간 설정", b: "격자 위를 드래그해서 세션 시간을 정해요. 칸 하나가 1분이고, 최대 45분까지 설정할 수 있어요. 시작 전이라면 언제든 조정 가능해요." },
        { t: "집중 대상 입력", b: "상단 입력칸에 지금 할 일을 적어요. 집중 대상을 명확히 쓰는 것만으로도 세션 중 흔들리지 않는 데 도움이 돼요." },
        { t: "시간이 흐르는 걸 봐요", b: "시작을 누르면 격자가 실시간으로 줄어들어요. 현재 진행 중인 칸은 초 단위로 천천히 비워지고, 1분이 지나면 사라져요." },
        { t: "진짜 쉬어요", b: "타이머가 끝나면 소리와 알림으로 알려드려요. 그 자리를 떠나세요. 휴식을 건너뛰지 마세요 — 쉬는 것도 집중의 일부예요." },
        { t: "장기집중", b: "'장기집중' 탭은 시간이 쌓이는 스톱워치예요. 목표 시간을 정하고 시작을 누르면 시간·분·초 그리드가 한 칸씩 차올라요. 이 탭이 열려 있을 때만 작동하고, 세션은 아카이브에 저장할 수 있어요." },
      ],
      dontShow: "뽀모도로 진입 시 자동으로 표시 안 함",
      showAgain: "가이드 보기",
      close: "집중 시작",
    },
    music: { off: "끄기", loopNote: "정지할 때까지 반복 재생" },
    guide: {
      btnLabel: "사용 방법",
      title: "기능 가이드",
      tabGuide: "가이드",
      tabContact: "문의",
      tabTerms: "약관",
      contactFormTitle: "메시지 보내기",
      contactSubjectPlaceholder: "제목",
      contactMessagePlaceholder: "궁금한 점이나 피드백을 남겨주세요…",
      contactBtn: "전송",
      contactSending: "전송 중…",
      contactSentConfirm: "메시지가 전송됐어요!",
      contactError: "전송에 실패했어요. 다시 시도해주세요.",
      contactHistory: "내 문의 내역",
      contactPending: "답변 대기",
      contactReplied: "답변 완료",
      contactAdminReply: "답변",
      sections: [
        {
          category: "전역",
          items: [
            { t: "테마 & 외관", b: "모든 화면 상단 바에서 6가지 테마(몬드리안, 해왕성, 화성, 지구, 금성, 수성), 다크/라이트 모드, 언어(EN/KO)를 전환할 수 있어요." },
            { t: "사운드 & 음악", b: "사운드 켜기/끄기와 배경 음악 선택이 가능해요. 음악은 직접 끄기 전까지 반복 재생돼요. 일부 음악은 Suno AI를 베이스로 추가 편집해 제작됐어요." },
            { t: "친구 & 공유", b: "프로필 페이지에서 친구 코드를 공유하세요. 추가된 친구는 내가 공개로 설정한 콘텐츠를 볼 수 있어요. 수정은 불가능하고 보기만 가능해요." },
            { t: "저장", b: "인터넷 연결이 안정적이면 자동으로 저장돼요. 중요한 작업 후에는 저장 버튼을 누르는 걸 권장해요. 새로고침하면 항상 홈 화면으로 돌아가요." },
          ],
        },
        {
          category: "플래너",
          items: [
            { t: "타임 블럭", b: "그리드를 드래그해 시간대를 선택하세요 — 한 칸이 30분이에요. 한 칸만 더블클릭해도 일정 추가가 가능해요." },
            { t: "일정 & 할 일", b: "일정은 특정 날짜에 연결돼요. 할 일은 날짜에 관계없이 전역으로 유지돼요. 체크하면 완료, ×로 삭제할 수 있어요." },
            { t: "월간 보기 & 반복 일정", b: "월간 탭에서 미래 날짜에 일정을 추가하거나 요일별 반복 일정을 설정할 수 있어요. 해당 요일이 되면 일간 보기에 자동으로 표시돼요." },
            { t: "자정 초기화", b: "일간 보기의 타임 블럭과 일정은 매일 자정에 초기화돼요. 할 일과 월간 캘린더 일정은 유지돼요." },
          ],
        },
        {
          category: "만다라트",
          items: [
            { t: "9×9 그리드", b: "중앙이 메인 목표예요. 주변 8칸은 하위 목표로, 각 바깥 블록의 중심 칸과 연결돼 있어요. 한쪽을 수정하면 다른 쪽도 자동으로 바뀌어요." },
            { t: "포커스 보기", b: "포커스 모드로 전환하면 왼쪽 미니맵을 보면서 한 블록씩 집중해서 편집할 수 있어요. 산만함 없이 하위 목표 하나에 깊이 집중하기 좋아요." },
            { t: "셀 메모", b: "세부 항목 칸의 메모 아이콘을 탭해 더 긴 메모를 추가할 수 있어요. 메모가 저장되면 칸에 작은 점이 표시돼요." },
            { t: "관리", b: "관리 페이지에서 여러 개의 만다라트를 만들 수 있어요. 각각 독립적으로 저장되고 개별 삭제도 가능해요." },
            { t: "공유", b: "만다라트를 공개로 설정하면 친구가 프로필 페이지에서 볼 수 있어요. 친구는 수정할 수 없어요." },
          ],
        },
        {
          category: "뽀모도로",
          items: [
            { t: "시간 설정", b: "그리드를 드래그해 세션 시간을 설정하세요. 한 칸이 1분 — 최대 45분이에요. 시작 전 언제든 조정 가능해요." },
            { t: "집중 목표", b: "상단 목표 칸에 지금 하는 일을 적어보세요. 목표를 이름으로 정하면 세션 내내 집중하는 데 도움이 돼요." },
            { t: "타이머", b: "시작을 누르면 그리드가 실시간으로 줄어들어요. 활성 칸이 초마다 비워지다가 1분이 지나면 사라져요." },
            { t: "휴식", b: "타이머가 끝나면 소리와 알림이 울려요. 잠깐 자리를 비우세요 — 휴식도 시스템의 일부예요." },
          ],
        },
      ],
    },
    splash: { cta: "클릭해서 나만의 만다라트 작성을 시작하세요." },
    next: "다음", prev: "이전", start: "작성 시작", skip: "건너뛰기",
    sound: "사운드", lang: "언어", theme: "테마", dark: "다크", light: "라이트",
    settings: "설정", notifications: "알림",
    install: {
      title: "GridA 설치",
      body: "홈 화면에 추가하면 앱처럼 바로 사용할 수 있어요.",
      install: "설치",
      iosHint: "하단",
      iosHint2: "버튼 → \"홈 화면에 추가\"",
    },
    pomodoro: {
      goalPlaceholder: "지금 무엇에 집중하나요?",
      start: "시작",
      pause: "일시정지",
      resume: "재개",
      reset: "초기화",
      done: "시간 종료!",
      minutesLeft: (n) => `${n}분 남음`,
      notifTitle: "'GridA' — 시간 종료!",
      notifBody: (goal) => goal ? `집중 세션 완료: "${goal}"` : "뽀모도로 세션이 종료됐어요.",
      notifPermission: "시간 종료 알림을 받으려면 알림 권한을 허용해주세요.",
      lockin: {
        modeTimer: "타이머",
        modeLockin: "장기집중",
        goalLabel: "목표 시간",
        goalSet: "목표 시간을 설정하고 시작을 누르세요.",
        start: "시작",
        pause: "일시정지",
        resume: "재개",
        reset: "초기화",
        save: "기록 저장",
        saved: "저장됨!",
        archive: "아카이브",
        congrats: "🎉 목표 달성 — 계속 가봅시다!",
        hint: "스톱워치는 이 탭이 열려 활성화된 동안에만 작동해요.",
        elapsed: "집중 시간",
        archiveTitle: "집중 아카이브",
        archiveEmpty: "아직 저장된 세션이 없어요.",
        close: "닫기",
        of: "/",
        unitH: "시간",
        unitM: "분",
        unitS: "초",
      },
      about: {
        title: "뽀모도로 기법이란?",
        body: [
          "뽀모도로 기법은 1980년대 후반 프란체스코 시릴로가 개발한 시간 관리 방법이에요. 보통 25분씩 집중하고 짧은 휴식을 반복해요. 이름은 그가 학생 시절 사용했던 토마토 모양 주방 타이머에서 따왔어요.",
          "GridA에서는 1칸이 1분이에요. 격자 위를 드래그해서 집중 시간을 설정하고, 시간이 지나면서 채워진 칸이 하나씩 사라지는 걸 보세요. 시각적인 리듬이 현재 순간에 집중하도록 도와줘요.",
          "세션 중에는 한 가지 일만 해요. 다른 생각이 떠오르면 메모해두고 휴식 시간에 처리하세요. 세션이 끝나면 진짜 휴식을 취하세요.",
        ],
        tipsTitle: "팁",
        tips: [
          "시작 전에 위 칸에 집중할 목표를 명확하게 적어보세요.",
          "다른 탭은 닫고 알림은 무음으로 설정하세요.",
          "집중이 흐트러져도 타이머를 다시 시작하지 말고 그냥 다시 집중하세요.",
          "세션 사이 휴식은 반드시 취하세요. 건너뛰지 마세요.",
        ],
        warningTitle: "주의",
        warning: "세션 중에는 멀티태스킹 금지예요. 집중 중에 떠오르는 일은 어딘가에 적어두고 휴식 시간에 처리하세요. 휴식 시간에도 중독성 짙은 콘텐츠(SNS, 영상 등)는 권장하지 않아요.",
      },
    },
  },
};
