export const T = {
  en: {
    title: "MANDALART",
    tagline: "ONE GOAL. EIGHT PATHS. SIXTY-FOUR STEPS.",
    loading: "Loading…",
    menu: { profile: "Profile", create: "New Mandalart", manage: "Manage", about: "What is Mandalart?" },
    back: "Back",
    replay: "Replay guide",
    categories: "Suggested categories",
    categoriesHint: "Tap one to drop it into an open slot",
    fullView: "Full grid",
    compactView: "Focus view",
    catList: [
      { k: "Health", d: "Sleep, fitness, nutrition" },
      { k: "Career", d: "Skills, role, milestones" },
      { k: "Finance", d: "Savings, income, habits" },
      { k: "Relationships", d: "Family, friends, community" },
      { k: "Growth", d: "Learning, mindset, reflection" },
      { k: "Hobby", d: "Creative outlets, play" },
      { k: "Mindset", d: "Discipline, calm, focus" },
      { k: "Travel", d: "Places, experiences" },
      { k: "Education", d: "Study, courses, knowledge" },
      { k: "Creativity", d: "Art, writing, music, design" },
      { k: "Spirituality", d: "Values, purpose, gratitude" },
      { k: "Social", d: "Networking, community impact" },
      { k: "Productivity", d: "Systems, tools, time management" },
      { k: "Leadership", d: "Influence, communication, vision" },
      { k: "Language", d: "Speaking, reading, listening" },
      { k: "Fitness", d: "Strength, flexibility, endurance" },
      { k: "Food", d: "Cooking, diet, meal habits" },
      { k: "Environment", d: "Space, organization, sustainability" },
      { k: "Rest", d: "Sleep, recovery, digital detox" },
      { k: "Passion Project", d: "Side venture, big idea, dream goal" },
    ],
    grid: {
      untitled: "Untitled Mandalart",
      mainGoal: "Main goal",
      subGoal: "Sub-goal",
      detail: "Detail",
      saving: "Saving…",
      savedJustNow: "Saved just now",
      savedAgo: (s) => `Saved ${s}s ago`,
      unsaved: "Unsaved changes",
      save: "Save",
      descTitle: "Add a short note",
      descViewTitle: "Note",
      descPlaceholder: "What does this step actually involve?",
      descSave: "Save",
      descCancel: "Cancel",
      descClose: "Close",
      visPrivate: "Private",
      visPublic: "Public",
      visHintPrivate: "Only you can see this.",
      visHintPublic: "Friends can view this (no editing).",
    },
    manage: {
      title: "Your Mandalarts",
      empty: "Nothing here yet — create your first one.",
      open: "Open",
      create: "+ New mandalart",
      delete: "Delete",
      deleteConfirm: "Delete this mandalart? This cannot be undone.",
      deleteYes: "Yes, delete",
      deleteNo: "Cancel",
    },
    auth: {
      email: "Email",
      password: "Password",
      username: "Display name",
      usernameHint: "This name cannot be changed once set.",
      signIn: "Sign in",
      signUp: "Create account",
      toSignUp: "New here? Create an account",
      toSignIn: "Already have an account? Sign in",
      signOut: "Sign out",
      signOutConfirm: "Are you sure you want to sign out?",
      signOutYes: "Sign out",
      signOutNo: "Cancel",
      deleteAccount: "Delete account",
      deleteAccountConfirm: "This will permanently delete your account and all data. This cannot be undone.",
      deleteAccountYes: "Delete permanently",
      deleteAccountNo: "Cancel",
      deleteAccountDeleting: "Deleting…",
      termsPrefix: "I agree to the",
      termsLink: "Terms of Use",
      termsRequired: "Please accept the Terms of Use to continue.",
      termsTitle: "Terms of Use",
      termsClauses: [
        "Your goal data is stored securely on Supabase servers. We do not sell or share your data with third parties.",
        "Your mandalarts are private by default. You control what is shared with friends.",
        "You may delete your account and all associated data at any time by contacting support.",
        "Do not use this service for any unlawful, harmful, or abusive purposes.",
        "This app is provided as-is. We are not liable for any loss of data or unintended use.",
      ],
    },
    friends: {
      yourCode: "Your friend code",
      copy: "Copy",
      copied: "Copied",
      addTitle: "Add a friend",
      placeholder: "Name#0000",
      add: "Add",
      exactHint: "Enter their exact code — there's no name search, just like a Battle Tag.",
      errSelf: "That's your own code.",
      errNotFound: "No one found with that code.",
      errAlready: "You're already connected with this code.",
      sent: (code) => `Friend request sent to ${code}.`,
      requests: "Friend requests",
      accept: "Accept",
      decline: "Decline",
      list: "Friends",
      empty: "No friends yet — add one above.",
      statusAccepted: "Friends",
      statusPending: "Pending",
      viewMandalarts: "View mandalarts",
      viewerListTitle: (code) => `${code}'s public mandalarts`,
      viewerEmpty: "This friend hasn't made anything public yet.",
      viewerOpen: "Open",
      viewerBadge: "Public · view only",
    },
    onboarding: [
      { t: "What is a Mandalart?", b: "A 9×9 grid built around one goal. Each of its 8 neighbors becomes the seed of its own surrounding grid." },
      { t: "The center converges", b: "The 8 cells around your main goal mirror the centers of the 8 outer blocks — edit either side and both update." },
      { t: "Write as if it's done", b: "Phrase entries in the present tense, as already achieved. It changes how you act toward them." },
      { t: "Make it yours", b: "Switch themes, toggle dark mode, play music while you write, and tag related cells to jump between them." },
      { t: "Ready", b: "Open a blank grid and place your first goal in the center." },
    ],
    about: {
      title: "What is Mandalart?",
      body: [
        "A Mandalart is a 9×9 grid goal-setting technique built around one central goal, broken into 8 sub-goals, each of which is further broken into 8 concrete action items. It originated in Japan in the 1980s and became widely known after baseball player Shohei Ohtani's own Mandalart from his high school years was publicized.",
        "This app's grid follows one rule: the 8 cells around your main goal are directly linked to the center cell of each of the 8 outer blocks — edit one and the other updates too. Eight separate paths, converging on one goal.",
        "Write entries in the present tense, as if already achieved, rather than as something you intend to do. It changes how you act toward them.",
      ],
      tipsTitle: "Quick tips",
      tips: [
        "Start with your main goal in the center. Make it specific and personal.",
        "Fill in the 8 surrounding sub-goals before touching any outer block.",
        "Use the suggested categories as a starting point, not a constraint.",
        "Link related cells with the ⛓ icon to jump between them instantly.",
        "Set your mandalart to Public so trusted friends can see your progress.",
        "Play background music to enter a focused, distraction-free writing state.",
      ],
      ohtaniLabel: "The Ohtani method",
      ohtani: "Shohei Ohtani created his Mandalart at age 16 with the goal of becoming a pro baseball player. His 8 sub-goals included nutrition, mental strength, speed, and pitching power — each broken into 8 daily habits. He achieved every one of them.",
    },
    gridTutorial: {
      steps: [
        { t: "Step 1 — Set your main goal", b: "Click the center cell of the center block and write your single most important goal. Be specific and personal." },
        { t: "Step 2 — Define 8 sub-goals", b: "The 8 cells around the center become your sub-goals. They automatically link to the centers of the 8 surrounding blocks." },
        { t: "Step 3 — Add 64 action items", b: "For each sub-goal block, fill its surrounding 8 cells with concrete daily actions. These are the habits that compound into real progress." },
        { t: "Write as if it's done", b: "Phrase every entry in the present tense — as if already achieved. It shifts how you think about and work toward each goal." },
        { t: "Full Grid vs Focus view", b: "Toggle between Full Grid (all 81 cells at once) and Focus view (one block at a time). In Focus view, use the minimap on the left to jump between blocks." },
        { t: "Track your progress", b: "Tap the circle check icon on any detail cell to mark it complete. The cell's background changes so you can see at a glance how far along you are." },
      ],
      dontShow: "Don't show this when creating new mandalarts",
      showAgain: "Show tutorial",
      close: "Got it, let's go",
    },
    music: { off: "Off", loopNote: "Loops until stopped" },
    guide: {
      btnLabel: "How to use",
      title: "Feature Guide",
      tabGuide: "Guide",
      tabContact: "Contact",
      contactFormTitle: "Send a message",
      contactSubjectPlaceholder: "Subject",
      contactMessagePlaceholder: "Describe your question or feedback…",
      contactBtn: "Send",
      contactSending: "Sending…",
      contactSentConfirm: "Message sent!",
      contactError: "Failed to send. Please try again.",
      contactHistory: "Your messages",
      contactPending: "Pending",
      contactReplied: "Replied",
      contactAdminReply: "Reply",
      items: [
        { t: "9×9 Grid", b: "The center cell is your main goal. The 8 cells around it are sub-goals — each one links directly to the center of an outer block. Edit either side and both update instantly." },
        { t: "Focus view", b: "Switch to Focus view to edit one block at a time with a minimap on the left side. Great for deep-diving into a single sub-goal without distraction." },
        { t: "Cell notes", b: "Tap the sticky-note icon on any detail cell to add a longer description or note. A small dot appears on the cell when a note is saved." },
        { t: "Themes & Music", b: "Switch between themes (Mondrian, Ink, Mocha, Sand) and toggle dark/light mode from the toolbar. Select a background music track — it loops until you stop it. Background tracks were created with Suno AI as a base and further edited by hand." },
        { t: "Friends & Sharing", b: "Share your friend code from the Profile page. Set a mandalart to Public so friends can view it. They cannot edit your mandalarts — view only." },
        { t: "Manage", b: "Create multiple mandalarts from the Manage page. Each one is saved separately and can be opened or deleted independently." },
      ],
    },
    next: "Next", prev: "Back", start: "Start writing", skip: "Skip",
    sound: "Sound", lang: "Language", theme: "Theme", dark: "Dark", light: "Light",
  },
  ko: {
    title: "MANDALART",
    tagline: "하나의 큰 목표. 8개의 소목표. 64개의 실행 방안.",
    loading: "불러오는 중…",
    menu: { profile: "프로필", create: "새 만다라트", manage: "만다라트 관리", about: "만다라트란?" },
    back: "뒤로",
    replay: "가이드 다시 보기",
    categories: "추천 카테고리",
    categoriesHint: "탭하면 빈 칸에 채워져요",
    fullView: "전체 보기",
    compactView: "포커스 보기",
    catList: [
      { k: "건강", d: "수면, 운동, 영양" },
      { k: "커리어", d: "역량, 직무, 마일스톤" },
      { k: "재정", d: "저축, 수입, 습관" },
      { k: "관계", d: "가족, 친구, 공동체" },
      { k: "성장", d: "학습, 마인드셋, 회고" },
      { k: "취미", d: "창작, 여가" },
      { k: "마인드셋", d: "규율, 평정심, 집중" },
      { k: "여행", d: "장소, 경험" },
      { k: "교육", d: "공부, 강의, 지식" },
      { k: "창의성", d: "미술, 글쓰기, 음악, 디자인" },
      { k: "영성", d: "가치관, 목적, 감사" },
      { k: "소셜", d: "네트워킹, 커뮤니티 참여" },
      { k: "생산성", d: "시스템, 도구, 시간 관리" },
      { k: "리더십", d: "영향력, 소통, 비전" },
      { k: "언어", d: "말하기, 읽기, 듣기" },
      { k: "체력", d: "근력, 유연성, 지구력" },
      { k: "식습관", d: "요리, 식단, 식사 습관" },
      { k: "환경", d: "공간, 정리, 지속가능성" },
      { k: "회복", d: "수면, 휴식, 디지털 디톡스" },
      { k: "사이드 프로젝트", d: "부업, 큰 아이디어, 꿈의 목표" },
    ],
    grid: {
      untitled: "제목 없는 만다라트",
      mainGoal: "메인 목표",
      subGoal: "하위 목표",
      detail: "세부 항목",
      saving: "저장 중…",
      savedJustNow: "방금 저장됨",
      savedAgo: (s) => `${s}초 전 저장됨`,
      unsaved: "저장되지 않은 변경사항",
      save: "저장",
      descTitle: "짧은 설명 추가",
      descViewTitle: "메모",
      descPlaceholder: "이 단계가 구체적으로 어떤 걸 의미하나요?",
      descSave: "저장",
      descCancel: "취소",
      descClose: "닫기",
      visPrivate: "비공개",
      visPublic: "공개",
      visHintPrivate: "나만 볼 수 있어요.",
      visHintPublic: "친구들이 볼 수 있어요 (수정은 불가).",
    },
    manage: {
      title: "내 만다라트",
      empty: "아직 없어요 — 첫 만다라트를 만들어보세요.",
      open: "열기",
      create: "+ 새 만다라트",
      delete: "삭제",
      deleteConfirm: "이 만다라트를 삭제할까요? 되돌릴 수 없어요.",
      deleteYes: "삭제",
      deleteNo: "취소",
    },
    auth: {
      email: "이메일",
      password: "비밀번호",
      username: "표시 이름",
      usernameHint: "한번 설정한 이름은 변경할 수 없어요.",
      signIn: "로그인",
      signUp: "계정 만들기",
      toSignUp: "처음이신가요? 계정 만들기",
      toSignIn: "이미 계정이 있으신가요? 로그인",
      signOut: "로그아웃",
      signOutConfirm: "정말 로그아웃 하시겠어요?",
      signOutYes: "로그아웃",
      signOutNo: "취소",
      deleteAccount: "계정 삭제",
      deleteAccountConfirm: "계정과 모든 데이터가 영구적으로 삭제되며 되돌릴 수 없어요.",
      deleteAccountYes: "영구 삭제",
      deleteAccountNo: "취소",
      deleteAccountDeleting: "삭제 중…",
      termsPrefix: "아래 이용약관에 동의해요:",
      termsLink: "이용약관",
      termsRequired: "계속하려면 이용약관에 동의해주세요.",
      termsTitle: "이용약관",
      termsClauses: [
        "작성하신 목표 데이터는 Supabase 서버에 안전하게 저장되며, 제3자에게 제공되거나 판매되지 않습니다.",
        "만다라트는 기본적으로 비공개입니다. 공유 여부는 직접 설정할 수 있습니다.",
        "언제든지 고객 지원을 통해 계정 및 모든 데이터를 삭제 요청할 수 있습니다.",
        "서비스를 불법적이거나 유해한 목적으로 사용하지 않습니다.",
        "이 앱은 현 상태로 제공되며, 데이터 손실이나 의도치 않은 사용으로 인한 책임을 지지 않습니다.",
      ],
    },
    friends: {
      yourCode: "내 친구 코드",
      copy: "복사",
      copied: "복사됨",
      addTitle: "친구 추가",
      placeholder: "이름#0000",
      add: "추가",
      exactHint: "정확한 코드를 입력해야 해요 — 이름으로는 검색할 수 없어요.",
      errSelf: "본인 코드예요.",
      errNotFound: "해당 코드를 가진 사용자가 없어요.",
      errAlready: "이미 연결된 코드예요.",
      sent: (code) => `${code}님께 친구 요청을 보냈어요.`,
      requests: "받은 친구 요청",
      accept: "수락",
      decline: "거절",
      list: "친구 목록",
      empty: "아직 친구가 없어요 — 위에서 추가해보세요.",
      statusAccepted: "친구",
      statusPending: "대기 중",
      viewMandalarts: "만다라트 보기",
      viewerListTitle: (code) => `${code}님의 공개 만다라트`,
      viewerEmpty: "아직 공개로 설정한 만다라트가 없어요.",
      viewerOpen: "열기",
      viewerBadge: "공개 · 보기 전용",
    },
    onboarding: [
      { t: "만다라트란?", b: "하나의 목표를 중심으로 펼쳐지는 9×9 그리드예요. 주변 8칸이 각각 새로운 블록의 씨앗이 되어 뻗어나가요." },
      { t: "연결된 구조", b: "메인 목표 둘레 8칸은 바깥 블록들의 중심 칸과 자동으로 연결돼요. 한쪽을 고치면 다른 쪽도 같이 바뀌어요." },
      { t: "이미 이룬 것처럼", b: "이미 이뤘다는 듯 현재형으로 적어보세요. 그렇게 쓴 문장이 생각과 행동을 함께 끌어당겨요." },
      { t: "내 스타일로", b: "테마와 다크모드를 바꾸고, 음악을 틀고, 연결된 칸을 태그해서 바로 이동해보세요." },
      { t: "시작할 준비 됐어요", b: "빈 그리드 중앙에 첫 번째 목표를 적어보세요." },
    ],
    about: {
      title: "만다라트란?",
      body: [
        "만다라트는 하나의 핵심 목표를 중심에 두고, 그것을 이루기 위한 8개의 하위 목표, 그리고 각 하위 목표를 다시 8개의 구체적인 실행 항목으로 쪼개는 9×9 격자 형태의 목표 설정 기법이에요. 1980년대 일본에서 만들어졌고, 야구선수 오타니 쇼헤이가 고교 시절 작성한 만다라트가 알려지면서 널리 퍼졌어요.",
        "이 앱의 그리드는 한 가지 원칙을 따라요 — 메인 목표 둘레의 8칸은 바깥에 있는 8개 블록 각각의 중심 칸과 그대로 연결돼 있어서, 한쪽을 고치면 다른 쪽도 같이 바뀌어요. 여덟 갈래로 흩어진 하위 목표들이 결국 하나의 중심으로 수렴한다는 뜻이에요.",
        "목표를 쓸 때는 '할 거야'가 아니라 '이미 하고 있어'처럼 현재형으로 적어보세요. 그렇게 쓴 말이 생각과 행동 모두를 바꿔요.",
      ],
      tipsTitle: "빠른 팁",
      tips: [
        "중앙에 메인 목표부터 적어보세요. 구체적이고 내 것이어야 해요.",
        "바깥 블록을 채우기 전에, 메인 목표 주변 8칸(하위 목표)부터 완성하세요.",
        "추천 카테고리는 출발점이지, 제약이 아니에요. 자유롭게 수정하세요.",
        "⛓ 아이콘으로 연관된 칸을 연결하면 한 번에 이동할 수 있어요.",
        "완성한 만다라트를 공개로 설정하면, 친구들과 목표를 나눌 수 있어요.",
        "배경 음악을 틀면 집중력 있는 글쓰기 상태에 더 쉽게 들어갈 수 있어요.",
      ],
      ohtaniLabel: "오타니 방식",
      ohtani: "오타니 쇼헤이는 16살에 '프로야구 선수가 되겠다'는 목표로 만다라트를 작성했어요. 영양, 멘탈, 스피드, 구위 등 8개의 하위 목표, 각각을 위한 64가지 일상 습관을 세웠고 — 모두 실현했습니다.",
    },
    gridTutorial: {
      steps: [
        { t: "Step 1 — 메인 목표 설정", b: "중앙 블록의 가운데 칸을 클릭해 가장 중요한 목표를 하나 적어요. 구체적이고 내 것이어야 해요." },
        { t: "Step 2 — 8개의 하위 목표", b: "중앙 칸 주변 8칸이 하위 목표가 돼요. 이 칸들은 바깥 8개 블록의 중심 칸과 자동으로 연결돼 있어요." },
        { t: "Step 3 — 64가지 실행 항목", b: "각 하위 목표 블록의 나머지 8칸에 구체적인 일상 행동을 적어요. 64가지 습관이 쌓여 진짜 변화가 만들어져요." },
        { t: "이미 이룬 것처럼 써요", b: "모든 항목을 현재형으로 — 이미 달성한 것처럼 적어보세요. 생각과 행동 방식이 달라져요." },
        { t: "전체 그리드 vs 포커스 뷰", b: "전체 그리드(81칸 한눈에 보기)와 포커스 뷰(블록 하나씩 집중 편집) 사이를 자유롭게 전환할 수 있어요. 포커스 뷰에서는 왼쪽 미니맵으로 블록 간 이동이 가능해요." },
        { t: "진행 상황 체크", b: "세부 실행 칸 오른쪽 아래의 동그라미 체크 아이콘을 눌러 완료 표시를 할 수 있어요. 배경색이 달라져서 얼마나 진행됐는지 한눈에 확인할 수 있어요." },
      ],
      dontShow: "다음부터 자동으로 표시 안 함",
      showAgain: "튜토리얼 보기",
      close: "시작하기",
    },
    music: { off: "끄기", loopNote: "정지할 때까지 반복 재생" },
    guide: {
      btnLabel: "사용 방법",
      title: "기능 가이드",
      tabGuide: "가이드",
      tabContact: "문의",
      contactFormTitle: "메시지 보내기",
      contactSubjectPlaceholder: "제목",
      contactMessagePlaceholder: "궁금한 점이나 피드백을 남겨주세요…",
      contactBtn: "전송",
      contactSending: "전송 중…",
      contactSentConfirm: "메시지가 전송됐어요!",
      contactError: "전송에 실패했어요. 다시 시도해주세요.",
      contactHistory: "내 문의 내역",
      contactPending: "답변 대기",
      contactReplied: "답변 완료",
      contactAdminReply: "답변",
      items: [
        { t: "9×9 그리드", b: "중앙이 메인 목표예요. 주변 8칸은 하위 목표로, 각각 바깥 블록의 중심 칸과 연결돼 있어요. 한쪽을 수정하면 다른 쪽도 자동으로 바뀌어요." },
        { t: "포커스 보기", b: "포커스 보기로 전환하면 왼쪽 미니맵을 보면서 한 블록씩 집중해서 편집할 수 있어요. 하나의 하위 목표에 깊이 집중하기 좋아요." },
        { t: "셀 메모", b: "세부 항목 칸의 메모 아이콘을 탭하면 더 긴 설명이나 메모를 추가할 수 있어요. 메모가 저장되면 칸에 작은 점이 표시돼요." },
        { t: "테마 & 음악", b: "상단 바에서 테마(몬드리안, 잉크, 모카, 샌드)와 다크/라이트 모드를 전환하세요. 배경음악을 선택하면 정지하기 전까지 반복 재생돼요. 배경음악은 Suno AI를 베이스로 직접 편집해 제작한 곡들이에요." },
        { t: "친구 & 공유", b: "프로필 페이지에서 친구 코드를 공유하세요. 만다라트를 공개로 설정하면 친구가 볼 수 있어요. 친구는 수정할 수 없고 보기만 가능해요." },
        { t: "만다라트 관리", b: "관리 페이지에서 여러 개의 만다라트를 만들 수 있어요. 각각 독립적으로 저장되고, 개별적으로 열거나 삭제할 수 있어요." },
      ],
    },
    next: "다음", prev: "이전", start: "작성 시작", skip: "건너뛰기",
    sound: "사운드", lang: "언어", theme: "테마", dark: "다크", light: "라이트",
  },
};
